
export const FETCH_LEAD = 'FETCH_LEAD';
export const FETCH_LEAD_SUCCESS = 'FETCH_LEAD_SUCCESS';
export const FETCH_LEAD_FAILURE = 'FETCH_LEAD_FAILURE';

export const REFETCH_LEAD = 'REFETCH_LEAD';
export const REFETCH_LEAD_SUCCESS = 'REFETCH_LEAD_SUCCESS';
export const REFETCH_LEAD_FAILURE = 'REFETCH_LEAD_FAILURE';

export const DELETE_LEAD = 'DELETE_LEAD';
export const DELETE_LEAD_SUCCESS = 'DELETE_LEAD_SUCCESS';
export const DELETE_LEAD_FAILURE = 'DELETE_LEAD_FAILURE';

export const ACTIONS = {
	FETCH_LEAD,
	FETCH_LEAD_SUCCESS,
	FETCH_LEAD_FAILURE,
	DELETE_LEAD,
	DELETE_LEAD_SUCCESS,
	DELETE_LEAD_FAILURE,
};