version: "3.2"
services:
  server:
    build: ./server
    volumes:
      - ./server:/app/server
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      - DJANGO_SETTINGS_MODULE=server.settings_prod
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: leadsdb
    volumes:
      - pgdata:/var/lib/postgresql/data/
  client:
    build: ./client
    volumes:
      - ./client:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - server
    command: yarn start
